# Generated by Django 4.2.4 on 2023-08-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoria',
            new_name='category',
        ),
    ]
